package com.xo.web.ext.tableau.models;
// Generated 27-Oct-2014 07:17:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import com.xo.web.models.system.AbstractEntity;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 * TableauWorkbook generated by hbm2java
 */
@SuppressWarnings("serial")
public class TableauWorkbook extends AbstractEntity {


     private String tableauWorkbookId;
     private TableauProject tableauProject;
     private String name;
     private String description;
     private Set<TableauView> tableauViews = new HashSet<TableauView>(0);

    public TableauWorkbook() {
    }

    public TableauWorkbook(String id,TableauProject tableauProject, boolean active) {
        this.tableauWorkbookId = id;
        this.tableauProject = tableauProject;
        this.active = active;
    }
    public TableauWorkbook(String id,TableauProject tableauProject, String name, String description, boolean active, Set<TableauView> tableauViewses) {
       this.tableauWorkbookId = id;
       this.tableauProject = tableauProject;
       this.name = name;
       this.description = description;
       this.active = active;
       this.tableauViews = tableauViewses;
    }

    public TableauWorkbook(WorkBook workBook) {
        this.tableauWorkbookId = workBook.id;
        this.name = workBook.name;
        this.displayName = workBook.name;
        this.description = workBook.description;
     }
    
    public String getTableauWorkbookId() {
        return this.tableauWorkbookId;
    }
    
    public void setTableauWorkbookId(String id) {
        this.tableauWorkbookId = id;
    }
    public TableauProject getTableauProject() {
        return this.tableauProject;
    }
    
    public void setTableauProject(TableauProject tableauProject) {
        this.tableauProject = tableauProject;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set<TableauView> getTableauViews() {
        return this.tableauViews;
    }
    
    public void setTableauViews(Set<TableauView> tableauViewses) {
        this.tableauViews = tableauViewses;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (tableauWorkbookId != null ? tableauWorkbookId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the tableauWorkbookId fields are not set
        if (!(object instanceof TableauWorkbook)) {
            return false;
        }
        TableauWorkbook other = (TableauWorkbook) object;
        if ((this.tableauWorkbookId == null && other.tableauWorkbookId != null) || (this.tableauWorkbookId != null && !this.tableauWorkbookId.equals(other.tableauWorkbookId))) {
            return false;
        }
        return true;
    }

    public String toString() {
    	return this.name;
    }

    public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.tableauWorkbookId, this.name);
	}

    public String getDisplayName() {
		return this.displayName != null ? this.displayName : this.name;
	}
}


