package com.xo.web.ext.tableau.models;
// Generated 27-Oct-2014 07:17:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import com.xo.web.models.system.AbstractEntity;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 * TableauProject generated by hbm2java
 */
@SuppressWarnings("serial")
public class TableauProject extends AbstractEntity {

     private String tableauProjectId;
     private TableauUser tableauUser;
     private String name;
     private Set<TableauWorkbook> tableauWorkbooks = new HashSet<TableauWorkbook>(0);

    public TableauProject() {
    }
	
    public TableauProject(String id, TableauUser tableauUsers) {
        this.tableauProjectId = id;
        this.tableauUser = tableauUsers;
    }

    public TableauProject(String id, TableauUser tableauUsers, String name, Set<TableauWorkbook> tableauWorkbooks) {
       this.tableauProjectId = id;
       this.tableauUser = tableauUsers;
       this.name = name;
       this.tableauWorkbooks = tableauWorkbooks;
    }

    public TableauProject(Project project) {
        this.tableauProjectId = project.id;
        this.name = project.name;
        this.displayName = project.name;
     }

    public String getTableauProjectId() {
        return this.tableauProjectId;
    }

    public void setTableauProjectId(String id) {
        this.tableauProjectId = id;
    }

    public TableauUser getTableauUser() {
        return this.tableauUser;
    }

    public void setTableauUser(TableauUser tableauUsers) {
        this.tableauUser = tableauUsers;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<TableauWorkbook> getTableauWorkbooks() {
        return this.tableauWorkbooks;
    }

    public void setTableauWorkbooks(Set<TableauWorkbook> tableauWorkbooks) {
        this.tableauWorkbooks = tableauWorkbooks;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (tableauProjectId != null ? tableauProjectId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the tableauProjectId fields are not set
        if (!(object instanceof TableauProject)) {
            return false;
        }
        TableauProject other = (TableauProject) object;
        if ((this.tableauProjectId == null && other.tableauProjectId != null) || (this.tableauProjectId != null && !this.tableauProjectId.equals(other.tableauProjectId))) {
            return false;
        }
        return true;
    }

    public String toString() {
    	return this.name;
    }

    public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.tableauProjectId, this.name);
	}

    public String getDisplayName() {
		return this.displayName != null ? this.displayName : this.name;
	}
}


