package com.xo.web.ext.tableau.models;
// Generated 27-Oct-2014 07:17:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.xo.web.models.system.AbstractEntity;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 *TableauSites generated by hbm2java
 */
@SuppressWarnings("serial")
public class TableauSite extends AbstractEntity {

     private String tableauSiteId;
     private String name;
     private String contentUrl;
     private Set<TableauUser> tableauUsers = new HashSet<TableauUser>(0);

    public TableauSite() {
    }

    public TableauSite(String id, boolean active) {
        this.tableauSiteId = id;
        this.active = active;
    }
    public TableauSite(String id, String name, String contentUrl, boolean active, Date lastModifiedDt, Date createdDt, Set<TableauUser> tableauUsers) {
       this.tableauSiteId = id;
       this.name = name;
       this.contentUrl = contentUrl;
       this.active = active;
       this.lastModifiedDate = lastModifiedDt;
       this.createdDate = createdDt;
       this.tableauUsers = tableauUsers;
    }

    public TableauSite(Site site) {
        this.tableauSiteId = site.id;
        this.name = site.siteName;
        this.contentUrl = site.contentUrl;
     }
    
    public String getTableauSiteId() {
        return this.tableauSiteId;
    }
    
    public void setTableauSiteId(String id) {
        this.tableauSiteId = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContentUrl() {
        return this.contentUrl;
    }
    
    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl;
    }

    public Set<TableauUser> getTableauUsers() {
        return this.tableauUsers;
    }
    
    public void setTableauUsers(Set<TableauUser> tableauUsers) {
        this.tableauUsers = tableauUsers;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (tableauSiteId != null ? tableauSiteId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the tableauSiteId fields are not set
        if (!(object instanceof TableauSite)) {
            return false;
        }
        TableauSite other = (TableauSite) object;
        if ((this.tableauSiteId == null && other.tableauSiteId != null) || (this.tableauSiteId != null && !this.tableauSiteId.equals(other.tableauSiteId))) {
            return false;
        }
        return true;
    }

    public String toString() {
    	return this.name;
    }

    public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.tableauSiteId, this.name);
	}

}


