package com.xo.web.ext.tableau.models;

import com.xo.web.models.system.AbstractEntity;
// Generated 27-Oct-2014 07:17:17 by Hibernate Tools 4.3.1
import com.xo.web.viewdtos.KeyValueDTO;



/**
 * TableauView generated by hbm2java
 */
@SuppressWarnings("serial")
public class TableauView extends AbstractEntity {

     private String tableauViewId;
     private TableauWorkbook tableauWorkbook;
     private String name;
     private boolean dashboard;
     private ViewGroup viewGroup;

    public TableauView(ViewGroup viewGroup, boolean Dashboard, String name, TableauWorkbook tableauWorkbook, String tableauViewId) {
        this.viewGroup = viewGroup;
        this.dashboard = Dashboard;
        this.name = name;
        this.tableauWorkbook = tableauWorkbook;
        this.tableauViewId = tableauViewId;
    }

    public ViewGroup getViewGroup() {
        return viewGroup;
    }

    public void setViewGroup(ViewGroup viewGroup) {
        this.viewGroup = viewGroup;
    }

    public boolean isDashboard() {
        return this.dashboard;
    }

    public void setDashboard(boolean dashboard) {
        this.dashboard = dashboard;
    }

    public TableauView() {
    }

    public TableauView(String id, TableauWorkbook tableauWorkbook) {
        this.tableauViewId = id;
        this.tableauWorkbook = tableauWorkbook;
    }
    public TableauView(String id, TableauWorkbook tableauWorkbook, String name, boolean i) {
       this.tableauViewId = id;
       this.tableauWorkbook = tableauWorkbook;
       this.name = name;
    }

    public TableauView(View view) {
        this.tableauViewId = view.id;
        this.name = view.name;
        this.displayName = view.name;
        this.displayOrder = 1;
     }

    public String getTableauViewId() {
        return this.tableauViewId;
    }

    public void setTableauViewId(String id) {
        this.tableauViewId = id;
    }
    public TableauWorkbook getTableauWorkbook() {
        return this.tableauWorkbook;
    }

    public void setTableauWorkbook(TableauWorkbook tableauWorkbook) {
        this.tableauWorkbook = tableauWorkbook;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (tableauViewId != null ? tableauViewId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the tableauViewId fields are not set
        if (!(object instanceof TableauView)) {
            return false;
        }
        TableauView other = (TableauView) object;
        if ((this.tableauViewId == null && other.tableauViewId != null) || (this.tableauViewId != null && !this.tableauViewId.equals(other.tableauViewId))) {
            return false;
        }
        return true;
    }

    public String toString() {
    	return this.name;
    }

    public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.tableauViewId, this.getDisplayName());
	}

    public String getDisplayName() {
		return this.displayName != null ? this.displayName : this.name;
	}
}


