package com.xo.web.ext.tableau.models;
// Generated 27-Oct-2014 07:17:17 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.xo.web.models.system.AbstractEntity;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 * TableauUser generated by hbm2java
 */
@SuppressWarnings("serial")
public class TableauUser extends AbstractEntity {


     private String tableauUserId;
     private TableauSite tableauSite;
     private String name;
     private String role;
     private boolean publish;
     private String contentAdmin;
     private Date lastLogin;
     private String externalAuthUserId;
     private Set<TableauProject> tableauProjects = new HashSet<TableauProject>(0);

    public TableauUser() {
    }

	
    public TableauUser(String id,TableauSite tableauSite, boolean publish) {
        this.tableauUserId = id;
        this.tableauSite = tableauSite;
        this.publish = publish;
    }
    public TableauUser(String id,TableauSite tableauSite, String name, String role, boolean publish, String contentAdmin, 
            Date lastLogin, String externalAuthUserId, Set<TableauProject> tableauProjects) {
       this.tableauUserId = id;
       this.tableauSite = tableauSite;
       this.name = name;
       this.role = role;
       this.publish = publish;
       this.contentAdmin = contentAdmin;
       this.lastLogin = lastLogin;
       this.externalAuthUserId = externalAuthUserId;
       this.tableauProjects = tableauProjects;
    }

    public TableauUser(User user) {
       this.tableauUserId = user.id;
       this.name = user.name;
       this.role = user.role;
       this.publish = Boolean.parseBoolean(user.publish);
       this.contentAdmin = user.contentAdmin;
       //this.lastLogin = user.lastLogin;
       this.externalAuthUserId = user.externalAuthUserId;
    }
    
    public String getTableauUserId() {
        return this.tableauUserId;
    }
    
    public void setTableauUserId(String id) {
        this.tableauUserId = id;
    }
    public TableauSite getTableauSite() {
        return this.tableauSite;
    }
    
    public void setTableauSite(TableauSite tableauSite) {
        this.tableauSite = tableauSite;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public boolean isPublish() {
        return this.publish;
    }
    
    public void setPublish(boolean publish) {
        this.publish = publish;
    }
    public String getContentAdmin() {
        return this.contentAdmin;
    }
    
    public void setContentAdmin(String contentAdmin) {
        this.contentAdmin = contentAdmin;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public String getExternalAuthUserId() {
        return this.externalAuthUserId;
    }
    
    public void setExternalAuthUserId(String externalAuthUserId) {
        this.externalAuthUserId = externalAuthUserId;
    }
    public Set<TableauProject> getTableauProjects() {
        return this.tableauProjects;
    }
    
    public void setTableauProjects(Set<TableauProject> tableauProjects) {
        this.tableauProjects = tableauProjects;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (tableauUserId != null ? tableauUserId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the tableauUserId fields are not set
        if (!(object instanceof TableauUser)) {
            return false;
        }
        TableauUser other = (TableauUser) object;
        if ((this.tableauUserId == null && other.tableauUserId != null) || (this.tableauUserId != null && !this.tableauUserId.equals(other.tableauUserId))) {
            return false;
        }
        return true;
    }

    public String toString() {
    	return this.name;
    }

    public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.tableauUserId, this.name);
	}
    
}


