package com.xo.web.models.system;
// Generated 22-Oct-2014 01:24:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang3.builder.HashCodeBuilder;

import com.xo.web.audit.Auditable;
import com.xo.web.viewdtos.KeyValueDTO;
/**
 * Permission generated by hbm2java
 */
@SuppressWarnings("serial")
@Auditable
public class ResourceType extends AbstractEntity {

     private Integer resourceTypeId;
     private String name;
     private String fullyQualifiedName;
     private String description;
     private Set<Permission> permissions = new HashSet<Permission>(0);
     private Set<ResourceFilter> resourceFilters = new HashSet<ResourceFilter>(0);

    public ResourceType() {
    }

    public Integer getResourceTypeId() {
        return this.resourceTypeId;
    }

    public void setResourceTypeId(Integer id) {
        this.resourceTypeId = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int hashCode() {
    	return new HashCodeBuilder().
    			append(this.resourceTypeId).
    			append(this.name).
    			append(this.description).
    			append(this.fullyQualifiedName).toHashCode();
    }

    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the resourceTypeId fields are not set
        if (!(object instanceof ResourceType)) {
            return false;
        }
        ResourceType other = (ResourceType) object;
        if ((this.resourceTypeId == null && other.resourceTypeId != null) || (this.resourceTypeId != null && !this.resourceTypeId.equals(other.resourceTypeId))) {
            return false;
        }
        return true;
    }

	public String getFullyQualifiedName() {
		return fullyQualifiedName;
	}

	public void setFullyQualifiedName(String fullyQualifiedName) {
		this.fullyQualifiedName = fullyQualifiedName;
	}

	public Set<Permission> getPermissions() {
		return permissions;
	}

	public void setPermissions(Set<Permission> permissions) {
		this.permissions = permissions;
	}

	public Set<ResourceFilter> getResourceFilters() {
		return resourceFilters;
	}

	public void setResourceFilters(Set<ResourceFilter> resourceFilters) {
		this.resourceFilters = resourceFilters;
	}

	public String toString() {
		return this.name;
	}

	public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.resourceTypeId, this.name);
	}
}


