package com.xo.web.models.system;
// Generated 22-Oct-2014 01:24:44 by Hibernate Tools 4.3.1

import org.apache.commons.lang3.builder.HashCodeBuilder;

import com.xo.web.audit.Auditable;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 * Permission generated by hbm2java
 */
@SuppressWarnings("serial")
@Auditable
public class ResourceFilterParameter  extends AbstractEntity {

	public static final String PARAM_TYPE_INT = "int";
	public static final String PARAM_TYPE_STRING = "string";

     private Integer resourceFilterParameterId;
     private String name;
     private String description;
     private ResourceFilterParamType paramType;
     private ResourceFilter resourceFilter;
     private Object parameterValues;

    public ResourceFilterParameter() {
    }

    public Integer getResourceFilterParameterId() {
        return this.resourceFilterParameterId;
    }
    
    public void setResourceFilterParameterId(Integer id) {
        this.resourceFilterParameterId = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public int hashCode() {
    	return new HashCodeBuilder().
    			append(this.resourceFilterParameterId).
    			append(this.name).
    			append(this.description).
    			append(this.paramType).
    			append(this.resourceFilter).toHashCode();
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the resourceFilterParameterId fields are not set
        if (!(object instanceof ResourceFilterParameter)) {
            return false;
        }
        ResourceFilterParameter other = (ResourceFilterParameter) object;
        if ((this.resourceFilterParameterId == null && other.resourceFilterParameterId != null) || (this.resourceFilterParameterId != null && !this.resourceFilterParameterId.equals(other.resourceFilterParameterId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return this.name;
    }

	public ResourceFilter getResourceFilter() {
		return resourceFilter;
	}

	public void setResourceFilter(ResourceFilter resourceType) {
		this.resourceFilter = resourceType;
	}

	public ResourceFilterParamType getParamType() {
		return paramType;
	}

	public void setParamType(ResourceFilterParamType paramType) {
		this.paramType = paramType;
	}

	public Object getParameterValues() {
		return parameterValues;
	}

	public void setParameterValues(Object parameterValues) {
		this.parameterValues = parameterValues;
	}

	public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.resourceFilterParameterId, this.name);
	}
}


