package com.xo.web.models.system;
// Generated 22-Oct-2014 01:24:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang3.builder.HashCodeBuilder;

import com.xo.web.audit.Auditable;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 * Permission generated by hbm2java
 */
@SuppressWarnings("serial")
@Auditable
public class ResourceFilter extends AbstractEntity {

     private Integer resourceFilterId;
     private String name;
     private String fullyQualifiedName;
     private String description;
     private ResourceType resourceType;
     private Set<ResourceFilterParameter> resourceFilterParameters = new HashSet<ResourceFilterParameter>(0);

    public ResourceFilter() {
    }

    public Integer getResourceFilterId() {
        return this.resourceFilterId;
    }

    public void setResourceFilterId(Integer id) {
        this.resourceFilterId = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int hashCode() {
        return new HashCodeBuilder().
        		append(this.resourceFilterId).
        		append(this.name).
        		append(this.description).
        		append(this.resourceType).toHashCode();
    }

    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the resourceFilterId fields are not set
        if (!(object instanceof ResourceFilter)) {
            return false;
        }
        ResourceFilter other = (ResourceFilter) object;
        if ((this.resourceFilterId == null && other.resourceFilterId != null) || (this.resourceFilterId != null && !this.resourceFilterId.equals(other.resourceFilterId))) {
            return false;
        }
        return true;
    }

	public String getFullyQualifiedName() {
		return fullyQualifiedName;
	}

	public void setFullyQualifiedName(String fullyQualifiedName) {
		this.fullyQualifiedName = fullyQualifiedName;
	}

	public Set<ResourceFilterParameter> getResourceFilterParameters() {
		return resourceFilterParameters;
	}

	public void setResourceFilterParameters(Set<ResourceFilterParameter> permissions) {
		this.resourceFilterParameters = permissions;
	}

	public ResourceType getResourceType() {
		return resourceType;
	}

	public void setResourceType(ResourceType resourceType) {
		this.resourceType = resourceType;
	}

	public String toString(){
		return this.name;
	}

	public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.resourceFilterId, this.name);
	}
}


