package com.xo.web.models.system;

import org.apache.commons.lang3.builder.HashCodeBuilder;
// Generated 18 Nov, 2014 11:54:37 AM by Hibernate Tools 4.3.1

import com.xo.web.viewdtos.KeyValueDTO;

/**
 * RolePermissionResourceInstance generated by hbm2java
 */
@SuppressWarnings("serial")
public class RolePermissionResourceInstance  extends AbstractEntity {

     private RolePermissionResourceInstanceId rolePermissionResourceInstanceId;
     private RolePermission rolePermission;
     private String displayText;

    public RolePermissionResourceInstance() {
    }

    public RolePermissionResourceInstance(RolePermission rolePermission, String resourceInstanceId, String displayText) {
    	if(rolePermission != null) {
    		this.rolePermissionResourceInstanceId = new RolePermissionResourceInstanceId(rolePermission.getRolePermissionId(), resourceInstanceId);
    	}
        this.rolePermission = rolePermission;
        this.displayText = displayText;
    }

    public RolePermissionResourceInstance(RolePermissionResourceInstanceId id, RolePermission rolePermission, String displayText, boolean active) {
        this.rolePermissionResourceInstanceId = id;
        this.rolePermission = rolePermission;
        this.displayText = displayText;
        this.active = active;
    }

    public RolePermissionResourceInstanceId getRolePermissionResourceInstanceId() {
        return this.rolePermissionResourceInstanceId;
    }
    
    public void setRolePermissionResourceInstanceId(RolePermissionResourceInstanceId id) {
        this.rolePermissionResourceInstanceId = id;
    }
    public RolePermission getRolePermission() {
        return this.rolePermission;
    }
    
    public void setRolePermission(RolePermission rolePermissions) {
        this.rolePermission = rolePermissions;
    }

    @Override
    public int hashCode() {
    	return new HashCodeBuilder().
        		append(this.rolePermissionResourceInstanceId).
        		append(this.rolePermission).toHashCode();
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the rolePermissionResourceInstanceId fields are not set
        if (!(object instanceof RolePermissionResourceInstance)) {
            return false;
        }
        RolePermissionResourceInstance other = (RolePermissionResourceInstance) object;
        if ((this.rolePermissionResourceInstanceId == null && other.rolePermissionResourceInstanceId != null) || (this.rolePermissionResourceInstanceId != null && !this.rolePermissionResourceInstanceId.equals(other.rolePermissionResourceInstanceId))) {
            return false;
        }
        return true;
    }

    public String toString() {
    	return displayText;
    }

	public String getDisplayText() {
		return displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.rolePermissionResourceInstanceId, this.displayText);
	}
}


