package com.xo.web.models.system;

import com.xo.web.viewdtos.KeyValueDTO;
// Generated 18 Nov, 2014 11:54:37 AM by Hibernate Tools 4.3.1



/**
 * UserPermissionResourceInstance generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserPermissionResourceInstance  extends AbstractEntity {

     private UserPermissionResourceInstanceId id;
     private UserPermission userPermission;
     private String displayText;

    public UserPermissionResourceInstance() {
    }

    public UserPermissionResourceInstance(UserPermission userPermission, String resourceInstanceId, String displayText) {
    	if(userPermission != null) {
    		this.id = new UserPermissionResourceInstanceId(userPermission.getUserPermissionId(), resourceInstanceId);
    	}
        this.userPermission = userPermission;
        this.displayText = displayText;
    }

    public UserPermissionResourceInstanceId getId() {
        return this.id;
    }

    public void setId(UserPermissionResourceInstanceId id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof UserPermissionResourceInstance)) {
            return false;
        }
        UserPermissionResourceInstance other = (UserPermissionResourceInstance) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

	public UserPermission getUserPermission() {
		return userPermission;
	}

	public void setUserPermission(UserPermission userPermission) {
		this.userPermission = userPermission;
	}

	public String toString() {
    	return displayText;
    }

	public String getDisplayText() {
		return displayText;
	}

	public void setDisplayText(
			String resourceInstanceDisplayText) {
		this.displayText = resourceInstanceDisplayText;
	}

	public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.id, this.displayText);
	}
}


