package com.xo.web.models.system;

import org.apache.commons.lang3.builder.HashCodeBuilder;
// Generated 18 Nov, 2014 11:54:37 AM by Hibernate Tools 4.3.1



/**
 * UserRoleId generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserRoleId  implements java.io.Serializable {


     private Integer userId;
     private Integer roleId;

    public UserRoleId() {
    }

    public UserRoleId(Integer userId, Integer roleId) {
       this.userId = userId;
       this.roleId = roleId;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserRoleId) ) return false;
		 UserRoleId castOther = ( UserRoleId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getRoleId()==castOther.getRoleId());
   }
   
   public int hashCode() {
	   return new HashCodeBuilder().
				append(this.userId).
				append(this.roleId).toHashCode();
   }   


}


