package com.xo.web.models.system;

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang3.builder.HashCodeBuilder;

import com.xo.web.util.XoUtil;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 * UserPermission generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserPermission extends AbstractEntity {

	private Integer userPermissionId;
	private Permission permission;
	private User user;
	private Set<UserPermissionResourceInstance> userPermissionResourceInstances = new HashSet<UserPermissionResourceInstance>(0);

	public UserPermission() {
	}

    public UserPermission(Permission permission, User user) {
    	if(XoUtil.isNotNull(permission, user)) {
    		this.permission = permission;
    		this.user = user;
    		this.active = true;
    	}
     }

	public Integer getUserPermissionId() {
		return this.userPermissionId;
	}

	public void setUserPermissionId(Integer id) {
		this.userPermissionId = id;
	}

	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permissions) {
		this.permission = permissions;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User users) {
		this.user = users;
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.userPermissionId).
				append(this.permission).
				append(this.user).
				append(this.active).toHashCode();
	}

	@Override
	public boolean equals(Object object) {
		// TODO: Warning - this method won't work in the case the userPermissionId fields are
		// not set
		if (!(object instanceof UserPermission)) {
			return false;
		}
		UserPermission other = (UserPermission) object;
		if ((this.userPermissionId == null && other.userPermissionId != null)
				|| (this.userPermissionId != null && !this.userPermissionId.equals(other.userPermissionId))) {
			return false;
		}
		return true;
	}

	public Set<UserPermissionResourceInstance> getUsersPermissionsResourceInstances() {
		return userPermissionResourceInstances;
	}

	public void setUsersPermissionsResourceInstances(
			Set<UserPermissionResourceInstance> userPermissionResourceInstances) {
		this.userPermissionResourceInstances = userPermissionResourceInstances;
	}

	public String toString() {
		return "Role:" + this.user.getFirstName() + ", Permission:" + this.permission.getName(); 
	}

	public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.userPermissionId, this.toString());
	}
}
