package com.xo.web.models.system;

import org.apache.commons.lang3.builder.HashCodeBuilder;

import com.xo.web.util.XoUtil;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 * UserRole generated by hbm2java
 */
@SuppressWarnings("serial")
public class UserRole  extends AbstractEntity {

     private UserRoleId userRoleId;
     private Role role;
     private User user;

    public UserRole() {
    }

    public UserRole(Role role, User user) {
    	if(XoUtil.isNotNull(role, user)) {
    		this.userRoleId = new UserRoleId(user.getUserId(), role.getRoleId());
    		this.role = role;
    		this.user = user;
    		this.active = true;
    	}
     }

    public UserRoleId getUserRoleId() {
        return this.userRoleId;
    }

    public void setUserRoleId(UserRoleId id) {
        this.userRoleId = id;
    }

    public Role getRole() {
        return this.role;
    }

    public void setRole(Role roles) {
        this.role = roles;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User users) {
        this.user = users;
    }

    @Override
    public int hashCode() {
    	return new HashCodeBuilder().append(this.userRoleId).
				append(this.role).
				append(this.user).toHashCode();
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the userRoleId fields are not set
        if (!(object instanceof UserRole)) {
            return false;
        }
        UserRole other = (UserRole) object;
        if ((this.userRoleId == null && other.userRoleId != null) || (this.userRoleId != null && !this.userRoleId.equals(other.userRoleId))) {
            return false;
        }
        return true;
    }

    public String toString() {
    	return "Role:" + this.user.getFirstName() + ", Role:" + this.role.getName();
    }

    public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.userRoleId, this.toString());
	}
}


