package com.xo.web.models.system;
// Generated 30 May, 2015 2:15:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang3.builder.HashCodeBuilder;

import com.xo.web.audit.Auditable;
import com.xo.web.viewdtos.KeyValueDTO;

/**
 * XoJob generated by hbm2java
 */
@SuppressWarnings("serial")
@Auditable
public class XoJob extends AbstractEntity {

     private Integer jobId;
     private String name;
     private String className;
     private Set<XoClientJobConfig> clientJobsConfigurations = new HashSet<XoClientJobConfig>(0);

    public XoJob() {
    }

    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String jobName) {
        this.name = jobName;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

    public Set<XoClientJobConfig> getClientJobsConfigurations() {
        return this.clientJobsConfigurations;
    }
    
    public void setClientJobsConfigurations(Set<XoClientJobConfig> clientJobsConfigurationses) {
        this.clientJobsConfigurations = clientJobsConfigurationses;
    }

    @Override
    public int hashCode() {
		return new HashCodeBuilder().append(this.jobId).
				append(this.name).
				append(this.className).toHashCode();
    }

    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the userId fields are not set
        if (!(object instanceof XoJob)) {
            return false;
        }
        XoJob other = (XoJob) object;
        if ((this.jobId == null && other.jobId != null) || (this.jobId != null && !this.jobId.equals(other.jobId))) {
            return false;
        }
        if ((this.name == null && other.name != null) || (this.name != null && !this.name.equals(other.name))) {
            return false;
        }
        if ((this.className == null && other.className != null) || (this.className != null && !this.className.equals(other.className))) {
            return false;
        }
        return true;
    }

    public String toString() {
    	return this.name;
    }

    public KeyValueDTO asKeyValue() {
		return new KeyValueDTO(this.jobId, this.name);
	}
}


