package com.xo.web.ext.chat.models;

import java.sql.Blob;
import java.util.Date;
// Generated 22-Oct-2014 01:24:44 by Hibernate Tools 4.3.1




import com.xo.web.models.system.AbstractEntity;
import com.xo.web.models.system.User;



/**
 * TokenAction generated by hbm2java
 */
@SuppressWarnings("serial")
public class Chat  extends AbstractEntity {

     private Integer messageId;
     private ChatRoom chatroom;
     private String type;
     private String message;
     private Date ts;
     private User user;
     private byte[] imagedata;

    public Chat() {
    }

    public Chat(ChatRoom chatroom,String message,String type,byte[] imagedata,Date ts,User user){
		this.chatroom = chatroom;
		this.message =message;
		this.imagedata=imagedata;
		this.ts = ts;
		this.user = user;
		this.type=type;
//		this.chatroom.getChat().add(this);
//		this.user.getChat().add(this);
    }
    
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer id) {
        this.messageId = id;
    }
    
    public byte[] getImagedata(){
    	return this.imagedata;
    }
    
    public void setImagedata(byte[] img) {
        this.imagedata = img;
    }
    
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User users) {
        this.user = users;
    }
    public ChatRoom getChatroom() {
        return this.chatroom;
    }
    
    public void setChatroom(ChatRoom chatroom) {
        this.chatroom = chatroom;
    }

    public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

    public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getTs() {
		return ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

}


